### ISSUE TITLE
Easy customization of generated code through YAML file

### ISSUE THREAD

**Issue by filipowm** [paultyng/go-unifi#235]
It would be nice to have simplified way of customizing generated code and fields, I mean this part in particular (ref: https://github.com/paultyng/go-unifi/blob/main/fields/main.go#L342-L452)
```go
switch resource.StructName {
		case "Account":
			resource.FieldProcessor = func(name string, f *FieldInfo) error {
				switch name {
				case "IP", "NetworkID":
					f.OmitEmpty = true
				}
				return nil
			}
		case "ChannelPlan":
			resource.FieldProcessor = func(name string, f *FieldInfo) error {
				switch name {
				case "Channel", "BackupChannel", "TxPower":
					if f.FieldType == "string" {
						f.CustomUnmarshalType = "numberOrString"
					}
				}
				return nil
			}
                (...)
}
```
so that it's easier to maintain and modify by external contributors. My idea is to be able to codify it in simple yaml file in following structure:
```yaml
customizations:
  <resource_name>:
    fields:
      _all: # meta marker to apply these changes to all
      <field_name>:
        fieldName: "" # override field name
        fieldType: "" # override field type
        customUnmarshalType: "" # override unmarshal type
        customUnmarshalFunc: "" # override unmarshal func
        omitEmpty: true # override omitEmpty flag
        ifFieldType: "" # apply changes only if field is of specified type
```

This way we could have `customizations.yml` like:
```yaml
customizations:
  Account:
    fields:
      IP:
        omitEmpty: true
      NetworkID:
        omitEmpty: true
  ChannelPlan:
    fields:
      Channel:
        ifFieldType: "string"
        customUnmarshalType: "numberOrString"
      BackupChannel:
        ifFieldType: "string"
        customUnmarshalType: "numberOrString"
      TxPower:
        ifFieldType: "string"
        customUnmarshalType: "numberOrString"
  Device:
    fields:
      _all:
        omitEmpty: true
      X:
        fieldType: "float64"
      Y:
        fieldType: "float64"
      StpPriority:
        fieldType: "string"
        customUnmarshalType: "numberOrString"
      Ht:
        fieldType: "int"
      Channel:
        customUnmarshalType: "numberOrString"
        ifFieldType: "string"
      BackupChannel:
        customUnmarshalType: "numberOrString"
        ifFieldType: "string"
      TxPower:
        customUnmarshalType: "numberOrString"
        ifFieldType: "string"
      LteExtAnt:
        customUnmarshalType: "booleanishString"
      LtePoe:
        customUnmarshalType: "booleanishString"
      PortOverrides:
        omitEmpty: false
```

Order of processing:
```mermaid
graph LR;
    all[_all customization]
    fields[field-specific customization]
    custom[coded customization]
    all-->fields-->custom
```
where each subsequent customization could amend previous ones.

What do you think @joshuaspence ? If you're fine with idea, I can jump on that and draft some code.
